### ISSUE TITLE
Adding OWASP ASVS  

### ISSUE THREAD

**Issue by snorlax19** [harisqazi1/Cybersecurity#8]
Hey, you should add OWASP ASVS. It's a comprehensive document with a lot of good resources. https://github.com/OWASP/ASVS 

You guys did an amazing job with this.

**Comment by yezz123** [comment]
> Hey, you should add OWASP ASVS. It's a comprehensive document with a lot of good resources. https://github.com/OWASP/ASVS
> 
> You guys did an amazing job with this.

Thank you @snorlax19  for the Idea it will be added soon! 🥇
